/* Veri hakları — REJİM DİLE BAĞLI (kullanıcı kararı, 2026-09-07):
   TR = KVKK (6698 s.K. m.10 aydınlatma + m.11 haklar), EN/NL = GDPR (Art. 13/14 + 15–22).
   Dil yargı yetkisiyle birebir örtüşmediği için her sürüm diğer rejime tek notla işaret eder.
   Kaynak: Mobil Onboarding v3 · O11 + Web v3 · W16.
   Açık rıza tercihleri burada DEĞİL — /account/consent'te (KVKK m.5/1 · GDPR Art. 6(1)(a)). */
import type { LegalBody } from "./types";

export const dataRights: LegalBody = {
  tr: [
    { note: "Bu metin aydınlatma amaçlıdır; açık rıza tercihlerin ayrı ekranda (Hesap → Açık rıza). Avrupa Ekonomik Alanı'ndaysan GDPR geçerlidir — bu sayfanın İngilizce ya da Hollandaca sürümü senin rejimini anlatır." },
    { h: "Veri sorumlusu" },
    { link: ["BumpInto (Mehmet Şerefoğlu) · [tacir adresi — mağazada görünür] · ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
    { h: "İşlenen kişisel veriler" },
    { ul: [
      "Kimlik ve iletişim: ad, e-posta, Google/Apple kimliği",
      "Konum: yalnız uygulama açıkken, ~1 km yuvarlanmış",
      "Ulaşım türü ve görünen ad",
      "Ses: yalnız aktarım anında, kaydedilmez",
      "Oturum geçmişi ve kullanım verisi (açarsan)",
    ] },
    { h: "İşleme amaçları" },
    { p: "Hesap oluşturma, adil orta nokta hesaplama, mekan arama, oturum ve buluşma kaydının yönetilmesi." },
    { h: "Aktarılan taraflar ve amaç" },
    { p: "Mekan arama ve adres çözümleme için Google, Foursquare ve OpenStreetMap Vakfı'na (yurt dışı) sorgu gönderilir. Sunucularımız AB'de barındırılır. Verin oturum dışındaki kişilerle ya da reklam amacıyla paylaşılmaz." },
    { h: "Toplama yöntemi ve hukuki sebep" },
    { p: "Hesap ve oturum verileri, sözleşmenin ifası için gereklidir (m.5/2-c). Konum ve mikrofon verisi ile kullanım verisi, açık rızana dayanır (m.5/1); rızanı istediğin an geri alabilirsin." },
    { h: "Saklama süresi" },
    { p: "Oturum verileri 24 saatte kapanır, 30 gün içinde silinir. Hesap verilerin, hesabını silene kadar tutulur." },
    { h: "İlgili kişinin hakları (m.11)" },
    { ul: [
      "İşlenip işlenmediğini öğrenme",
      "İşlenmişse buna ilişkin bilgi talep etme",
      "İşleme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme",
      "Yurt içi/yurt dışı aktarıldığı üçüncü kişileri bilme",
      "Eksik/yanlış işlenmişse düzeltilmesini isteme",
      "Silinmesini veya yok edilmesini isteme",
      "Düzeltme/silme işleminin aktarılan taraflara bildirilmesini isteme",
      "Otomatik analiz sonucu aleyhe çıkan sonuca itiraz etme",
    ] },
    { h: "Başvuru ve şikâyet" },
    { link: ["Talebini şu adrese yaz, başvurunu en geç 30 gün içinde sonuçlandırırız: ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
    { p: "Başvurun reddedilirse ya da yanıtı yetersiz bulursan Kişisel Verileri Koruma Kurulu'na şikâyette bulunabilirsin." },
  ],
  en: [
    { note: "This page explains how we inform you and what you can demand; your consent choices live on a separate screen (Account → Consent). If you are in Türkiye, KVKK (Law 6698) applies — the Turkish version of this page describes that regime." },
    { h: "Controller" },
    { link: ["BumpInto (Mehmet Şerefoğlu) · [trader address — shown in the stores] · ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
    { h: "Personal data we process" },
    { ul: [
      "Identity and contact: name, email, Google/Apple identifier",
      "Location: only while the app is open, rounded to ~1 km",
      "Travel mode and display name",
      "Voice: only while it is being transmitted, never recorded",
      "Session history and usage data (if you turn it on)",
    ] },
    { h: "Purposes" },
    { p: "Creating your account, computing a fair midpoint, searching for places, and managing your sessions and meet-ups." },
    { h: "Legal bases (Art. 6)" },
    { p: "Account and session data: performance of our contract with you, Art. 6(1)(b). Location, microphone and usage data: your consent, Art. 6(1)(a) — you may withdraw it at any time, which does not affect processing already carried out." },
    { h: "Recipients and international transfers" },
    { p: "We send place and address queries to Google, Foursquare and the OpenStreetMap Foundation. Our servers are hosted in the EU; queries may reach providers outside the EEA (including the United States) under the European Commission's standard contractual clauses. Your data is never shared outside your session or for advertising." },
    { h: "Retention" },
    { p: "Session data closes after 24 hours and is deleted within 30 days. Account data is kept until you delete your account; deletion closes access immediately and rows are erased within 30 days." },
    { h: "Your rights (Art. 15–22)" },
    { ul: [
      "Access — obtain a copy of the data we hold about you (Art. 15)",
      "Rectification — have inaccurate data corrected (Art. 16)",
      "Erasure — have your data deleted (Art. 17)",
      "Restriction — have processing limited while a dispute is resolved (Art. 18)",
      "Portability — receive your data in a machine-readable format (Art. 20)",
      "Object — object to processing based on legitimate interests (Art. 21)",
      "Withdraw consent — at any time, for consent-based processing (Art. 7(3))",
      "Not be subject to a decision based solely on automated processing (Art. 22)",
    ] },
    { h: "How to exercise them, and how to complain" },
    { link: ["Write to us and we will respond within one month: ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
    { p: "You may also lodge a complaint with your national supervisory authority — in the Netherlands, the Autoriteit Persoonsgegevens." },
  ],
  nl: [
    { note: "Deze pagina legt uit hoe we je informeren en wat je kunt eisen; je toestemmingskeuzes staan op een apart scherm (Account → Toestemming). Ben je in Turkije, dan geldt de KVKK (wet 6698) — de Turkse versie van deze pagina beschrijft dat regime." },
    { h: "Verwerkingsverantwoordelijke" },
    { link: ["BumpInto (Mehmet Şerefoğlu) · [handelsadres — zichtbaar in de stores] · ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
    { h: "Persoonsgegevens die we verwerken" },
    { ul: [
      "Identiteit en contact: naam, e-mail, Google/Apple-identificatie",
      "Locatie: alleen als de app open is, afgerond op ~1 km",
      "Vervoerswijze en weergavenaam",
      "Spraak: alleen tijdens de overdracht, wordt niet opgenomen",
      "Sessiegeschiedenis en gebruiksgegevens (als je dit aanzet)",
    ] },
    { h: "Doeleinden" },
    { p: "Je account aanmaken, een eerlijk middelpunt berekenen, plekken zoeken en je sessies en afspraken beheren." },
    { h: "Rechtsgronden (art. 6)" },
    { p: "Account- en sessiegegevens: uitvoering van onze overeenkomst met jou, art. 6 lid 1 onder b. Locatie, microfoon en gebruiksgegevens: jouw toestemming, art. 6 lid 1 onder a — je kunt die altijd intrekken, zonder gevolgen voor de verwerking die al heeft plaatsgevonden." },
    { h: "Ontvangers en doorgifte naar het buitenland" },
    { p: "We sturen plaats- en adreszoekopdrachten naar Google, Foursquare en de OpenStreetMap Foundation. Onze servers staan in de EU; zoekopdrachten kunnen aanbieders buiten de EER bereiken (waaronder de Verenigde Staten), op basis van de modelcontractbepalingen van de Europese Commissie. Je gegevens worden nooit buiten je sessie of voor advertenties gedeeld." },
    { h: "Bewaartermijn" },
    { p: "Sessiegegevens sluiten na 24 uur en worden binnen 30 dagen verwijderd. Accountgegevens bewaren we tot je je account verwijdert; verwijderen sluit de toegang direct af en de gegevens worden binnen 30 dagen gewist." },
    { h: "Jouw rechten (art. 15–22)" },
    { ul: [
      "Inzage — een kopie opvragen van de gegevens die we over je hebben (art. 15)",
      "Rectificatie — onjuiste gegevens laten corrigeren (art. 16)",
      "Wissing — je gegevens laten verwijderen (art. 17)",
      "Beperking — de verwerking laten beperken zolang een geschil loopt (art. 18)",
      "Overdraagbaarheid — je gegevens in een machineleesbaar formaat ontvangen (art. 20)",
      "Bezwaar — bezwaar maken tegen verwerking op grond van gerechtvaardigd belang (art. 21)",
      "Toestemming intrekken — op elk moment, bij verwerking op basis van toestemming (art. 7 lid 3)",
      "Niet onderworpen worden aan uitsluitend geautomatiseerde besluitvorming (art. 22)",
    ] },
    { h: "Hoe je ze uitoefent en waar je klaagt" },
    { link: ["Mail ons; we reageren binnen één maand: ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
    { p: "Je kunt ook een klacht indienen bij je nationale toezichthouder — in Nederland de Autoriteit Persoonsgegevens." },
  ],
};
