/* Kaynak: Mobil Onboarding v3 · O9 + Web v3 · W14. Üç dilde tam metin.
   GDPR Art. 13/14 bilgilendirmesi AYRI dokümanda değil BURADA ve /data-rights'ta durur. */
import type { LegalBody } from "./types";

export const privacy: LegalBody = {
  tr: [
    { h: "Neyi topluyoruz" },
    { table: [
      ["Hesap", "Ad, e-posta, Google/Apple kimliği"],
      ["Konum", "Yalnız uygulama açıkken · ~1 km yuvarlanarak paylaşılır"],
      ["Ulaşım türü", "Yürüyüş, bisiklet, araba vb. — yol süresi için"],
      ["Görünen ad", "Oturumdaki herkese görünür"],
      ["Ses", "Kaydedilmez; cihazlar arası doğrudan (P2P) akar"],
      ["Oturum geçmişi", "24 saatte kapanır, 30 günde silinir"],
      ["Kullanım verisi", "Yalnız sen Ayarlar'dan açarsan toplanır"],
    ] },
    { h: "Neden topluyoruz" },
    { p: "Herkese adil bir orta nokta bulmak, çevredeki mekanları aramak ve oturumunu listende tutmak için. Bunların dışında bir amaçla kullanmayız." },
    { h: "Hukuki dayanak" },
    { p: "Hesap ve oturum verileri sözleşmenin ifası için işlenir. Konum, mikrofon ve kullanım verisi yalnızca açık rızana dayanır; rızanı Hesap → Açık rıza ekranından istediğin an geri alabilirsin." },
    { h: "Kimlerle paylaşıyoruz" },
    { p: "Konumun ve görünen adın yalnızca aynı oturumdaki kişilerle paylaşılır. Mekan aramak için Google Places, Foursquare ve OpenStreetMap/Nominatim'e sorgu göndeririz; bu sorgularda kimliğin yer almaz. Verini reklam ağlarına satmayız, paylaşmayız." },
    { h: "Yurt dışına aktarım" },
    { p: "Sunucularımız Avrupa Birliği'nde barındırılır. Mekan ve adres sorguları, hizmet sağlayıcıların bulunduğu ülkelere (ABD dahil) gidebilir; bu sorgular kimliğini içermez." },
    { h: "Ne kadar tutuyoruz" },
    { p: "Oturumlar 24 saatte kapanır, 30 gün sonra kalıcı olarak silinir. Hesap bilgilerin, hesabını silene kadar tutulur; sildiğinde erişim anında kapanır ve satırlar 30 gün içinde kalıcı olarak silinir." },
    { h: "Hakların" },
    { link: ["Verilerine erişme, düzeltme ve silme hakkın var; ayrıntısı Veri hakların sayfasında. Uygulama içinde Hesap → Hesabı sil ile başlayabilir, ya da ", "bumpinto.app/account/delete", "/account/delete"] },
    { h: "Çocuklar" },
    { p: "BumpInto 13 yaşın altındaki kullanıcılar için tasarlanmamıştır; bilerek onlardan veri toplamayız." },
    { h: "İletişim" },
    { link: ["Sorun mu var: ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
  ],
  en: [
    { h: "What we collect" },
    { table: [
      ["Account", "Name, email, Google/Apple identifier"],
      ["Location", "Only while the app is open · shared rounded to ~1 km"],
      ["Travel mode", "Walking, cycling, driving — used for travel times"],
      ["Display name", "Visible to everyone in the session"],
      ["Voice", "Never recorded; streams directly between devices (P2P)"],
      ["Session history", "Closes after 24 hours, deleted after 30 days"],
      ["Usage data", "Collected only if you turn it on in Settings"],
    ] },
    { h: "Why we collect it" },
    { p: "To find a midpoint that is fair to everyone, search for nearby places, and keep your session in your list. We do not use it for anything else." },
    { h: "Legal basis" },
    { p: "Account and session data are processed to perform our contract with you (GDPR Art. 6(1)(b)). Location, microphone and usage data rest solely on your consent (Art. 6(1)(a)); you can withdraw that consent at any time under Account → Consent, without affecting processing already carried out." },
    { h: "Who we share it with" },
    { p: "Your location and display name are shared only with people in the same session. To search for places we send queries to Google Places, Foursquare and OpenStreetMap/Nominatim; those queries do not carry your identity. We never sell or share your data with advertising networks." },
    { h: "International transfers" },
    { p: "Our servers are hosted in the European Union. Place and address lookups may reach providers outside the EEA (including the United States) under the European Commission's standard contractual clauses; those lookups do not carry your identity." },
    { h: "How long we keep it" },
    { p: "Sessions close after 24 hours and are permanently deleted after 30 days. Account data is kept until you delete your account; deletion closes access immediately and the rows are permanently erased within 30 days." },
    { h: "Your rights" },
    { link: ["You can access, correct and erase your data — see Your data rights for the full list. Start in the app under Account → Delete account, or at ", "bumpinto.app/account/delete", "/account/delete"] },
    { h: "Children" },
    { p: "BumpInto is not designed for users under 13, and we do not knowingly collect data from them." },
    { h: "Contact" },
    { link: ["Something wrong? Write to ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
  ],
  nl: [
    { h: "Wat we verzamelen" },
    { table: [
      ["Account", "Naam, e-mail, Google/Apple-identificatie"],
      ["Locatie", "Alleen als de app open is · gedeeld afgerond op ~1 km"],
      ["Vervoerswijze", "Lopen, fietsen, auto — voor reistijden"],
      ["Weergavenaam", "Zichtbaar voor iedereen in de sessie"],
      ["Spraak", "Wordt niet opgenomen; loopt rechtstreeks tussen apparaten (P2P)"],
      ["Sessiegeschiedenis", "Sluit na 24 uur, wordt na 30 dagen verwijderd"],
      ["Gebruiksgegevens", "Alleen als je dit zelf aanzet in Instellingen"],
    ] },
    { h: "Waarom we het verzamelen" },
    { p: "Om een middelpunt te vinden dat voor iedereen eerlijk is, plekken in de buurt te zoeken en je sessie in je lijst te houden. Voor niets anders." },
    { h: "Rechtsgrond" },
    { p: "Account- en sessiegegevens verwerken we om onze overeenkomst met jou uit te voeren (AVG art. 6 lid 1 onder b). Locatie, microfoon en gebruiksgegevens berusten uitsluitend op jouw toestemming (art. 6 lid 1 onder a); je kunt die toestemming altijd intrekken via Account → Toestemming, zonder gevolgen voor de verwerking die al heeft plaatsgevonden." },
    { h: "Met wie we delen" },
    { p: "Je locatie en weergavenaam worden alleen gedeeld met mensen in dezelfde sessie. Voor het zoeken naar plekken sturen we zoekopdrachten naar Google Places, Foursquare en OpenStreetMap/Nominatim; die bevatten je identiteit niet. We verkopen of delen je gegevens nooit met advertentienetwerken." },
    { h: "Doorgifte naar het buitenland" },
    { p: "Onze servers staan in de Europese Unie. Plaats- en adreszoekopdrachten kunnen aanbieders buiten de EER bereiken (waaronder de Verenigde Staten), op basis van de modelcontractbepalingen van de Europese Commissie; die zoekopdrachten bevatten je identiteit niet." },
    { h: "Hoe lang we het bewaren" },
    { p: "Sessies sluiten na 24 uur en worden na 30 dagen definitief verwijderd. Accountgegevens bewaren we tot je je account verwijdert; verwijderen sluit de toegang direct af en de gegevens worden binnen 30 dagen definitief gewist." },
    { h: "Jouw rechten" },
    { link: ["Je kunt je gegevens inzien, corrigeren en laten wissen — de volledige lijst staat bij Jouw gegevensrechten. Begin in de app via Account → Account verwijderen, of op ", "bumpinto.app/account/delete", "/account/delete"] },
    { h: "Kinderen" },
    { p: "BumpInto is niet bedoeld voor gebruikers jonger dan 13 jaar; we verzamelen niet bewust gegevens van hen." },
    { h: "Contact" },
    { link: ["Iets mis? Mail naar ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
  ],
};
