/* Kaynak: Mobil Onboarding v3 · O10 + Web v3 · W15. Üç dilde tam metin. */
import type { LegalBody } from "./types";

export const terms: LegalBody = {
  tr: [
    { h: "Hizmet" },
    { p: "BumpInto, arkadaşlarınla adil bir buluşma noktası ve mekan bulmanı sağlar. Mekan bilgileri (saat, fiyat, puan) üçüncü taraf sağlayıcılardan gelir; bunlar önceden haber vermeden değişebilir. Doğruluğunu garanti etmeyiz — gitmeden önce kontrol et." },
    { h: "Hesap ve davet linkleri" },
    { p: "Davet linkini paylaştığın kişilerden sorumlusun. Bir oturum 24 saat içinde otomatik kapanır; kapanan bir linke yeniden katılamazsın." },
    { h: "Kabul edilebilir kullanım" },
    { p: "Taciz, nefret söylemi, spam ve sahte kimlik yasaktır. Sesli sohbette ve görünen adlarda rahatsız edici içeriğe sıfır toleransımız var. Bir kişiyi bildirebilir ya da engelleyebilirsin; ihlal tespit edilirse hesabın uyarısız kapatılabilir." },
    { h: "İçerik" },
    { p: "Oturum adı ve görünen adın sana aittir. Bize yalnızca bunları uygulama içinde göstermemiz için sınırlı bir lisans verirsin." },
    { h: "Sorumluluk sınırı" },
    { p: "BumpInto bir buluşma aracıdır; taraflar arasında ne olduğundan sorumlu değiliz. Hizmeti olduğu gibi sunarız, kesintisiz çalışacağını garanti etmeyiz." },
    { h: "Fesih" },
    { p: "Şartları ihlal edersen hesabını askıya alabilir ya da kapatabiliriz. Sen de hesabını istediğin an kapatabilirsin." },
    { h: "Değişiklikler" },
    { p: "Bu şartları güncelleyebiliriz; önemli değişikliklerde uygulama içinden bilgilendiririz." },
    { h: "Uygulanacak hukuk" },
    { p: "Türkiye ve Hollanda'daki tüketici haklarını saklı tutarız; bu şartlar seni yasal haklarından mahrum bırakmaz." },
    { h: "İletişim" },
    { link: ["Sorun mu var: ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
  ],
  en: [
    { h: "The service" },
    { p: "BumpInto helps you and your friends find a fair meeting point and a place to go. Place details (opening hours, price, rating) come from third-party providers and can change without notice. We do not guarantee their accuracy — check before you set off." },
    { h: "Accounts and invite links" },
    { p: "You are responsible for whom you share an invite link with. A session closes automatically within 24 hours; once it has closed, the link can no longer be joined." },
    { h: "Acceptable use" },
    { p: "Harassment, hate speech, spam and impersonation are forbidden. We have zero tolerance for abusive content in voice chat and in display names. You can report or block someone; if we find a violation, your account may be closed without notice." },
    { h: "Content" },
    { p: "Your session name and display name remain yours. You grant us only a limited licence to show them inside the app." },
    { h: "Limitation of liability" },
    { p: "BumpInto is a tool for meeting up; we are not responsible for what happens between the people who meet. The service is provided as is, and we do not guarantee uninterrupted availability." },
    { h: "Termination" },
    { p: "If you breach these terms we may suspend or close your account. You can close your account whenever you like." },
    { h: "Changes" },
    { p: "We may update these terms; for significant changes we will tell you inside the app." },
    { h: "Governing law" },
    { p: "Consumer rights in Türkiye and the Netherlands are reserved; nothing in these terms deprives you of rights the law gives you." },
    { h: "Contact" },
    { link: ["Something wrong? Write to ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
  ],
  nl: [
    { h: "De dienst" },
    { p: "Met BumpInto vind je samen met vrienden een eerlijk ontmoetingspunt en een plek om heen te gaan. Gegevens over plekken (openingstijden, prijs, beoordeling) komen van derden en kunnen zonder aankondiging veranderen. We garanderen de juistheid niet — controleer het voordat je vertrekt." },
    { h: "Account en uitnodigingslinks" },
    { p: "Je bent zelf verantwoordelijk voor met wie je een uitnodigingslink deelt. Een sessie sluit automatisch binnen 24 uur; daarna kun je niet meer via die link deelnemen." },
    { h: "Toegestaan gebruik" },
    { p: "Intimidatie, haatzaaien, spam en identiteitsfraude zijn verboden. Voor kwetsende inhoud in spraakchat en in weergavenamen geldt nultolerantie. Je kunt iemand melden of blokkeren; bij een geconstateerde overtreding kan je account zonder waarschuwing worden gesloten." },
    { h: "Inhoud" },
    { p: "Je sessienaam en weergavenaam blijven van jou. Je geeft ons alleen een beperkte licentie om ze binnen de app te tonen." },
    { h: "Beperking van aansprakelijkheid" },
    { p: "BumpInto is een hulpmiddel om af te spreken; wij zijn niet verantwoordelijk voor wat er tussen de deelnemers gebeurt. We leveren de dienst zoals die is en garanderen geen ononderbroken beschikbaarheid." },
    { h: "Beëindiging" },
    { p: "Bij schending van deze voorwaarden kunnen we je account opschorten of sluiten. Zelf kun je je account op elk moment sluiten." },
    { h: "Wijzigingen" },
    { p: "We kunnen deze voorwaarden bijwerken; bij belangrijke wijzigingen laten we het in de app weten." },
    { h: "Toepasselijk recht" },
    { p: "Consumentenrechten in Turkije en Nederland blijven van kracht; deze voorwaarden ontnemen je geen wettelijke rechten." },
    { h: "Contact" },
    { link: ["Iets mis? Mail naar ", "hello@bumpinto.app", "mailto:hello@bumpinto.app"] },
  ],
};
